In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.4 MB 4.0 MB/s eta 0:00:03
   ------ --------------------------------- 2.1/12.4 MB 4.2 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.4 MB 4.1 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.4 MB 3.8 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.4 MB 4.0 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.4 MB 4.1 MB/s eta 0:00:02
   --------------------- ------------------ 6.6/12.4 MB 4.1 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.4 MB 4.2 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.4 MB 4.3 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.4 MB 4.4 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.4 MB 4.4 MB/s eta 0:00:01
   ---------

In [2]:
import numpy as np

In [3]:
random_int_array = np.random.randint(1, 50, size=(10,1))
random_int_array

array([[13],
       [18],
       [39],
       [30],
       [17],
       [26],
       [ 7],
       [46],
       [45],
       [25]], dtype=int32)

ex1

In [9]:
random_int_array.dtype

dtype('int32')

In [10]:
np.ndim(random_int_array)

2

In [11]:
random_int_array.shape

(10, 1)

In [12]:
random_int_array.size

10

ex2

In [15]:
matrix=np.random.randint(10, 100, size=(2,5))

In [16]:
matrix

array([[69, 89, 61, 88, 21],
       [31, 33, 63, 28, 14]], dtype=int32)

In [18]:
matrix.shape


(2, 5)

ex2

In [34]:
arr1=np.array([[1,5,9],[1,5,9]])

In [20]:
arr1

([1, 5, 9], [1, 5, 9], [1, 5, 9])

In [33]:
arr2=np.array([[1,5,9],[1,5,9]])

In [36]:
arr3=arr1+arr2

In [37]:
arr3

array([[ 2, 10, 18],
       [ 2, 10, 18]])

In [38]:
np.median(arr3)

np.float64(10.0)

ex3

In [43]:
arr=np.random.randint(1, 100, size=20)

In [44]:
arr

array([ 5, 81, 81,  4, 37, 66, 89, 40, 10, 64, 29, 69, 74, 13, 25, 32, 62,
       61, 15, 18], dtype=int32)

In [45]:
condition = arr > 50
filtered_arr = arr[condition]
filtered_arr



array([81, 81, 66, 89, 64, 69, 74, 62, 61], dtype=int32)

ex4

In [48]:
numbers = list(range(1, 11))

In [50]:
import random

In [51]:
random.shuffle(numbers)

In [52]:
numbers

[8, 1, 6, 10, 9, 5, 3, 7, 2, 4]